version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nova_senha
      POSTGRES_DB: sales
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:nova_senha@localhost:5435/sales?schema=public"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm start

volumes:
  postgres-data:
